package com.opentypeless.android.rime.userdata;

import android.content.Context;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Arrays;
import java.util.Objects;
import java.util.concurrent.Semaphore;
import java.util.regex.Pattern;

/**
 * App-private, no-backup Rime UserDB directory with one bounded local recovery point.
 *
 * <p>The checkpoint contains only root-level {@code *.userdb} trees. Deployed Schema/cache files
 * stay outside the recovery point and are regenerated by librime from the separately validated
 * resource package.</p>
 */
public final class RimeUserDataStore {
    private static final String ROOT_NAME = "rime_user_data_v1";
    private static final String CURRENT_NAME = "current";
    private static final String CHECKPOINT_NAME = "checkpoint";
    private static final String CHECKPOINT_NEW = ".checkpoint-new";
    private static final String CHECKPOINT_OLD = ".checkpoint-old";
    private static final String RESTORE_NEW = ".restore-new";
    private static final String RESTORE_OLD = ".restore-old";
    private static final int MAXIMUM_FILES = 2_048;
    private static final long MAXIMUM_FILE_BYTES = 16L * 1024L * 1024L;
    private static final long MAXIMUM_TOTAL_BYTES = 64L * 1024L * 1024L;
    private static final int MAXIMUM_DEPTH = 16;
    private static final Pattern USERDB_NAME = Pattern.compile(
            "[A-Za-z0-9][A-Za-z0-9._-]{0,126}\\.userdb");
    private static final Semaphore LIFECYCLE_LEASE = new Semaphore(1, true);

    public record Status(boolean hasUserData, boolean hasCheckpoint, int fileCount, long totalBytes) {
        public Status {
            if (fileCount < 0 || totalBytes < 0) throw new IllegalArgumentException();
        }
    }

    public final class Session implements AutoCloseable {
        private boolean closed;

        private Session() {}

        public File userDirectory() {
            requireOpen();
            return childUnchecked(root, CURRENT_NAME);
        }

        /** Replaces the previous recovery point with a bounded copy of current UserDB trees. */
        public void checkpoint() throws RimeUserDataException {
            requireOpen();
            checkpointInternal();
        }

        /** Restores the latest complete checkpoint while retaining the same exclusive lease. */
        public void restoreLatestCheckpoint() throws RimeUserDataException {
            requireOpen();
            restoreInternal();
        }

        @Override
        public void close() {
            if (closed) return;
            closed = true;
            LIFECYCLE_LEASE.release();
        }

        private void requireOpen() {
            if (closed) {
                throw new IllegalStateException("Rime UserDB session is closed");
            }
        }
    }

    private final File root;

    public RimeUserDataStore(Context context) {
        this(new File(Objects.requireNonNull(context, "context").getNoBackupFilesDir(), ROOT_NAME));
    }

    RimeUserDataStore(File root) {
        this.root = Objects.requireNonNull(root, "root");
    }

    /** Acquires the only process-local native/UserDB lease. */
    public Session openSession() throws RimeUserDataException {
        if (!LIFECYCLE_LEASE.tryAcquire()) throw new RimeUserDataException(
                RimeUserDataException.Code.BUSY);
        boolean success = false;
        try {
            requireRoot();
            recoverInterruptedOperations();
            requireDirectory(child(root, CURRENT_NAME));
            success = true;
            return new Session();
        } finally {
            if (!success) LIFECYCLE_LEASE.release();
        }
    }

    public Status status() throws RimeUserDataException {
        if (!LIFECYCLE_LEASE.tryAcquire()) throw new RimeUserDataException(
                RimeUserDataException.Code.BUSY);
        try {
            requireRoot();
            recoverInterruptedOperations();
            File current = child(root, CURRENT_NAME);
            File checkpoint = child(root, CHECKPOINT_NAME);
            Scan scan = scanUserData(current, false);
            return new Status(scan.roots > 0, hasCompleteCheckpoint(checkpoint),
                    scan.files, scan.bytes);
        } finally {
            LIFECYCLE_LEASE.release();
        }
    }

    public void restoreLatestCheckpoint() throws RimeUserDataException {
        if (!LIFECYCLE_LEASE.tryAcquire()) throw new RimeUserDataException(
                RimeUserDataException.Code.BUSY);
        try {
            requireRoot();
            recoverInterruptedOperations();
            restoreInternal();
        } finally {
            LIFECYCLE_LEASE.release();
        }
    }

    public void clear() throws RimeUserDataException {
        if (!LIFECYCLE_LEASE.tryAcquire()) throw new RimeUserDataException(
                RimeUserDataException.Code.BUSY);
        try {
            requireRoot();
            recoverInterruptedOperations();
            deleteTreeRequired(child(root, CURRENT_NAME));
            deleteTreeRequired(child(root, CHECKPOINT_NAME));
            deleteTreeRequired(child(root, CHECKPOINT_NEW));
            deleteTreeRequired(child(root, CHECKPOINT_OLD));
            deleteTreeRequired(child(root, RESTORE_NEW));
            deleteTreeRequired(child(root, RESTORE_OLD));
            requireDirectory(child(root, CURRENT_NAME));
        } finally {
            LIFECYCLE_LEASE.release();
        }
    }

    private void checkpointInternal() throws RimeUserDataException {
        File current = child(root, CURRENT_NAME);
        File checkpoint = child(root, CHECKPOINT_NAME);
        File next = child(root, CHECKPOINT_NEW);
        File old = child(root, CHECKPOINT_OLD);
        deleteTreeRequired(next);
        deleteTreeRequired(old);
        requireDirectory(next);
        copyUserData(current, next);
        if (checkpoint.exists() && !checkpoint.renameTo(old)) failStorage();
        if (!next.renameTo(checkpoint)) {
            if (old.exists() && !old.renameTo(checkpoint)) failStorage();
            failStorage();
        }
        deleteTreeRequired(old);
    }

    private void restoreInternal() throws RimeUserDataException {
        File checkpoint = child(root, CHECKPOINT_NAME);
        if (!hasCompleteCheckpoint(checkpoint)) {
            throw new RimeUserDataException(RimeUserDataException.Code.NO_CHECKPOINT);
        }
        File current = child(root, CURRENT_NAME);
        File next = child(root, RESTORE_NEW);
        File old = child(root, RESTORE_OLD);
        deleteTreeRequired(next);
        deleteTreeRequired(old);
        requireDirectory(next);
        copyUserData(checkpoint, next);
        if (current.exists() && !current.renameTo(old)) failStorage();
        if (!next.renameTo(current)) {
            if (old.exists() && !old.renameTo(current)) failStorage();
            failStorage();
        }
        deleteTreeRequired(old);
    }

    private void recoverInterruptedOperations() throws RimeUserDataException {
        File current = child(root, CURRENT_NAME);
        File checkpoint = child(root, CHECKPOINT_NAME);
        File checkpointNew = child(root, CHECKPOINT_NEW);
        File checkpointOld = child(root, CHECKPOINT_OLD);
        File restoreNew = child(root, RESTORE_NEW);
        File restoreOld = child(root, RESTORE_OLD);

        deleteTreeRequired(checkpointNew);
        if (!checkpoint.exists() && checkpointOld.exists()
                && !checkpointOld.renameTo(checkpoint)) failStorage();
        if (checkpoint.exists()) deleteTreeRequired(checkpointOld);
        deleteTreeRequired(restoreNew);
        if (!current.exists() && restoreOld.exists() && !restoreOld.renameTo(current)) failStorage();
        if (current.exists()) deleteTreeRequired(restoreOld);
    }

    private static boolean hasCompleteCheckpoint(File checkpoint) throws RimeUserDataException {
        return checkpoint.isDirectory() && scanUserData(checkpoint, true).roots > 0;
    }

    private static void copyUserData(File source, File target) throws RimeUserDataException {
        if (!source.isDirectory()) return;
        File[] children = listed(source);
        int roots = 0;
        for (File child : children) {
            if (!USERDB_NAME.matcher(child.getName()).matches()) continue;
            roots++;
            copyNode(child, new File(target, child.getName()), 1, new MutableBounds());
        }
        if (roots == 0) {
            // An empty checkpoint is never considered restorable, but remains a valid sync point.
            return;
        }
        scanUserData(target, true);
    }

    private static void copyNode(File source, File target, int depth, MutableBounds bounds)
            throws RimeUserDataException {
        if (depth > MAXIMUM_DEPTH || Files.isSymbolicLink(source.toPath())) failLimit();
        try {
            File canonicalSource = source.getCanonicalFile();
            if (source.isDirectory()) {
                requireDirectory(target);
                for (File child : listed(source)) {
                    copyNode(child, new File(target, child.getName()), depth + 1, bounds);
                }
                return;
            }
            if (!source.isFile() || !canonicalSource.equals(source.getAbsoluteFile().getCanonicalFile())) {
                failLimit();
            }
            long length = source.length();
            bounds.add(length);
            try (FileInputStream input = new FileInputStream(source);
                 FileOutputStream output = new FileOutputStream(target)) {
                byte[] buffer = new byte[16_384];
                int read;
                while ((read = input.read(buffer)) != -1) {
                    if (read > 0) output.write(buffer, 0, read);
                }
                output.getFD().sync();
            }
        } catch (IOException | SecurityException error) {
            throw new RimeUserDataException(RimeUserDataException.Code.STORAGE_FAILED, error);
        }
    }

    private static Scan scanUserData(File directory, boolean requireOnlyUserDb)
            throws RimeUserDataException {
        if (!directory.isDirectory()) return new Scan(0, 0, 0L);
        MutableBounds bounds = new MutableBounds();
        int roots = 0;
        for (File child : listed(directory)) {
            if (!USERDB_NAME.matcher(child.getName()).matches()) {
                if (requireOnlyUserDb) failLimit();
                continue;
            }
            roots++;
            scanNode(child, 1, bounds);
        }
        return new Scan(roots, bounds.files, bounds.bytes);
    }

    private static void scanNode(File node, int depth, MutableBounds bounds)
            throws RimeUserDataException {
        if (depth > MAXIMUM_DEPTH || Files.isSymbolicLink(node.toPath())) failLimit();
        try {
            if (node.isDirectory()) {
                for (File child : listed(node)) scanNode(child, depth + 1, bounds);
            } else if (node.isFile()
                    && node.getCanonicalFile().equals(node.getAbsoluteFile().getCanonicalFile())) {
                bounds.add(node.length());
            } else {
                failLimit();
            }
        } catch (IOException | SecurityException error) {
            throw new RimeUserDataException(RimeUserDataException.Code.STORAGE_FAILED, error);
        }
    }

    private static File[] listed(File directory) throws RimeUserDataException {
        File[] children = directory.listFiles();
        if (children == null) failStorage();
        Arrays.sort(children, java.util.Comparator.comparing(File::getName));
        return children;
    }

    private void requireRoot() throws RimeUserDataException {
        requireDirectory(root);
        try {
            if (Files.isSymbolicLink(root.toPath())
                    || !root.getCanonicalFile().equals(root.getAbsoluteFile().getCanonicalFile())) {
                failStorage();
            }
        } catch (IOException | SecurityException error) {
            throw new RimeUserDataException(RimeUserDataException.Code.STORAGE_FAILED, error);
        }
    }

    private static File child(File parent, String name) throws RimeUserDataException {
        try {
            File canonicalParent = parent.getCanonicalFile();
            File result = new File(canonicalParent, name).getCanonicalFile();
            if (!result.getPath().startsWith(canonicalParent.getPath() + File.separator)) failStorage();
            return result;
        } catch (IOException | SecurityException error) {
            throw new RimeUserDataException(RimeUserDataException.Code.STORAGE_FAILED, error);
        }
    }

    private static File childUnchecked(File parent, String name) {
        return new File(parent, name);
    }

    private static void requireDirectory(File directory) throws RimeUserDataException {
        if ((!directory.isDirectory() && !directory.mkdirs()) || !directory.isDirectory()
                || Files.isSymbolicLink(directory.toPath())) failStorage();
    }

    private static void deleteTreeRequired(File file) throws RimeUserDataException {
        if (file == null || !file.exists()) return;
        if (Files.isSymbolicLink(file.toPath())) failStorage();
        if (file.isDirectory()) {
            for (File child : listed(file)) deleteTreeRequired(child);
        }
        if (!file.delete() && file.exists()) failStorage();
    }

    private static void failStorage() throws RimeUserDataException {
        throw new RimeUserDataException(RimeUserDataException.Code.STORAGE_FAILED);
    }

    private static void failLimit() throws RimeUserDataException {
        throw new RimeUserDataException(RimeUserDataException.Code.LIMIT_EXCEEDED);
    }

    private static final class MutableBounds {
        int files;
        long bytes;

        void add(long length) throws RimeUserDataException {
            if (length < 0 || length > MAXIMUM_FILE_BYTES
                    || files >= MAXIMUM_FILES || bytes > MAXIMUM_TOTAL_BYTES - length) failLimit();
            files++;
            bytes += length;
        }
    }

    private record Scan(int roots, int files, long bytes) {}
}
